name: Library + Storybook Build

# on all branches
on: [push]

jobs:
  frontend_compile:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install deps
        run: yarn
      - name: Run Prettier
        run: yarn run format
      - name: Run ESLint
        run: yarn run lint
      - name: Build component Library
        run: yarn run build
      - name: Build Storybook
        run: yarn run build-storybook
        env:
            NODE_OPTIONS: "--max_old_space_size=4096" # to get around JavaScript heap out of memory error

